[tool.black]
target-version = ["py312"]
line-length = 130
skip-magic-trailing-comma = false

[tool.ruff]
target-version = "py312"
line-length = 130
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
preview = true
select = ["F", "E", "W", "I", "UP", "ANN", "A", "C4", "G", "Q", "SLF", "SIM", "TCH", "FIX", "RUF"]
ignore = ["ANN002", "ANN003", "ANN204", "E702", "UP030", "UP032", "I001"]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
